### ISSUE TITLE
Reading a line is actually an interaction with the user

### ISSUE THREAD

**Issue by AlexKap23** [dayo92/SoltMachine#15]
https://github.com/dayo92/SoltMachine/blob/93fce74994024f8020edeb08eb6679291d7d8b33/SoltMachine/Program.cs#L56-L67

In this block of code you are getting an input from the code and you are validating it. It could be easily in a method and this method could be located on UIMethods.cs as there's an interaction with the user.

This issue can be used and as a template to implement more methods like this.

**Comment by dayo92** [comment]
Close as this was done with previous commit
