### ISSUE TITLE
DiagonalMatch 2 is overriding the result of DiagonalMatch1

### ISSUE THREAD

**Issue by AlexKap23** [dayo92/SoltMachine#16]
https://github.com/dayo92/SoltMachine/blob/93fce74994024f8020edeb08eb6679291d7d8b33/SoltMachine/Program.cs#L137

What would happen if you had a matchFound = true because of a DiagonalMatch1 and a matchFound=false because of DiagonalMatch2?

matchFound = CheckDiagonalMatch2(numbers) -> overrides the result of matchFound = CheckDiagonalMatch1(numbers);

**Comment by dayo92** [comment]
Fixed with
