### ISSUE TITLE
Bad naming

### ISSUE THREAD

**Issue by incredibleLeitman** [dayo92/SoltMachine#19]
https://github.com/dayo92/SoltMachine/blob/aa6f8cd68cd1927dc18b515e68d1b54aa753879e/SoltMachine/UIMethods.cs#L7
(besides the spelling error) your functions have bad naming 👆 

All functions should start with a verb that indicates *what* is happening.
Just nouns are usually used for classes
-> "GameTitle" contain a string that holds the title of the game
-> whereas "PrintGameTitle" shows the text on the console

It is a common and good way to come up with a few common verbs in your program that you use for methods that do similar things like
"Print", "Show", "Display", ... for methods that print stuff to the console,
or "Get", "AskFor", "Accept", "Request", ... for methods that retrieve input from the user

This will make your code very consistent and easy to read, for other developers and also you in the future :D

**Comment by incredibleLeitman** [comment]
This issue is relevant for all your files/methods :D

For example you still have functions called "AvailableBalance", "BettingQuestion", ... what should be "Print..."

Even worse is this one 
https://github.com/dayo92/SoltMachine/blob/e8e6e6c8179337cf1c9a2bad979153cebbdbaef0/SoltMachine/UIMethods.cs#L62
>_<

**Comment by AlexKap23** [comment]
As @incredibleLeitman has mentioned, this issue applies to all files and methods. UIMethods.cs has not been touched :P

You should apply method naming convensions to every single method in this file

**Comment by dayo92** [comment]
changed naming conventions with last commit
